name: "Build"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node.
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 12.x
      - name: Install and build.
        run: |
          npm ci
          npm run export
        env:
          CI: true
      - name: Deploy!
        uses: demurgos/ga-deploy-git@v1
        if: ${{ github.event_name == 'push' }}
        with:
          accessToken: ${{ secrets.PUSH_TOKEN }}
          commitUser: "DeployBot"
          destBranch: "gh-pages"
          srcDir: "out"
